version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - ML_SERVICE_URL=http://ml-service:5000
    depends_on:
      - ml-service

  ml-service:
    build: ./ml-service
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend